### ISSUE TITLE
Generate summary section when no differences are found

### ISSUE THREAD

**Issue by aeroyorch** [aide/aide#114]
Hello,

We are parsing the output of aide (version 0.16) in order to monitor possible changes in our cluster and we would like to know if there is any way of generating the summary report when no differences are found. I.e.:

> Summary:
  Total number of entries:  ...
  Added entries:                0
  Removed entries:              0
  Changed entries:              0

Thank you in advance,
Jorge

**Comment by hvhaugwitz** [comment]
AIDE v0.16 has been released several years ago, please update to the latest version.

Since v0.17 `aide` outputs the following (with `report_level=summary`) when no differences are found:
```
Start timestamp: 2021-11-09 19:03:13 +0100 (AIDE 0.17.3)
AIDE found NO differences between database and filesystem. Looks okay!!
Report level: summary

Number of entries:      1234

End timestamp: 2021-11-09 19:03:13 +0100 (run time: 0m 0s)
```

Please contact the AIDE user mailing list (https://www.ipi.fi/mailman/listinfo/aide) for any further question about the usage of AIDE.
