### ISSUE TITLE
Documented configuration parameter "syslog_format = true" not working. 

### ISSUE THREAD

**Issue by deftoner** [aide/aide#139]
the aide.conf parameter syslog_format is not working. (Man page: https://www.mankier.com/5/aide.conf)

No matter where I insert it in config file. the error is always
`ERROR: /etc/aide/aide.conf:111: group 'true' is not defined (line: 'syslog_format = true')

Ubuntu 22.04.1 LTS
installed from repository (apt install aide)

**Comment by hvhaugwitz** [comment]
AIDE does not provide a `syslog_format` configuration option (see `man 5 aide.conf` or [doc/aide.conf.5](https://github.com/aide/aide/blob/master/doc/aide.conf.5)).

Your referenced manual page is outdated and probably references the manual page provided in the customized RedHat package of `aide`.

The misleading error message has been fixed in f64b582a59eddcee41dbe013fa92bb653a2969cc.

**Comment by deftoner** [comment]
Hello @hvhaugwitz thank you for the quick reply, and sorry for the misunderstanding. I saw the same issue on a post on ubuntu too. In any case can I bother you with the question if there is a replacement or a way so AIDE can send one line errors to syslog? 

THANKS!

**Comment by hvhaugwitz** [comment]
No, there is no such report format in AIDE. Feel free to create a feature request for a new `report_format` option.

Error messages are always written to `stderr` .
