### ISSUE TITLE
Segmentation fault when check

### ISSUE THREAD

**Issue by mvasi90** [aide/aide#80]
```
./aide --check
Segmentation fault (core dumped)
```
But `--update` and `--init` works.

Config file
```
database=file:aide.db.gz
database_out=file:aide.db.new.gz
database_new=file:aide.db.cmp.gz
gzip_dbout=yes
verbose=20
report_url=file:aide.log
report_url=stdout

/   R
```

**Comment by hvhaugwitz** [comment]
Is this related to #75? Can you reproduce this with `--disable-static` configure option?

**Comment by mvasi90** [comment]
That is what I'm doing now.
Yes, it works.

Thank you very much for your time. Have a nice day.

**Comment by mvasi90** [comment]
Man, I give up.
`aide` no longer works. It keeps giving me the same error (segmentation fault) even though I have compiled it on the same machine and even if it is dynamic. This does not always happen and at first I have not detected it. I thought it was fixed by compiling, but no.

I am going to make the same decision as the Arch Linux developers and I will abandon this software.
I am going to create my own intrusion detection system in rust or golang.

Thank you for your help and your time.

**Comment by hvhaugwitz** [comment]
I can't understand why you are thinking Arch Linux has abandoned `AIDE`. The latest release is available via `AUR`[0] and it was not available for some time because there was no active maintainer[1].

Try the version packaged for your distro and contact the maintainer for any distro-specific issue. If you can narrow down your segfaults to AIDE itself, you can open a issue here with guidance how to reproduce the behaviour. Otherwise I can't help you.

Additionally as said multiple times you can contact the AIDE user mailing list[2] to get help or advice from other AIDE users.

[0] https://aur.archlinux.org/packages/aide/
[1] https://bbs.archlinux.org/viewtopic.php?id=255309
[2](https://www.ipi.fi/mailman/listinfo/aide

**Comment by mvasi90** [comment]
> I can't understand why you are thinking Arch Linux has abandoned AIDE. The latest release is available via AUR[0] and it was not available for some time because there was no active maintainer[1].

The community repository has removed `aide` from the official repository this year.
Arch User Repository AUR is not official. And the packages does not have vulnerability checks.
https://security.archlinux.org/package/aide

> Warning: AUR packages are user produced content. Any use of the provided files is at your own risk.
https://wiki.archlinux.org/index.php/Arch_User_Repository

> Try the version packaged for your distro and contact the maintainer for any distro-specific issue. 

The package is downloaded directly as tar.gz.
I have tested (manually with git) the latest release `0.16.2`, commit: `a8a5d67f4abb230df850f7b327b1f373e7ec49cf (tag: v0.16.2)` compiled dynamically and it works.

**Comment by Zugschlus** [comment]
aide 0.16.2 is not the lastest release. Which git repository are you referring to?

**Comment by mvasi90** [comment]
> aide 0.16.2 is not the lastest release. Which git repository are you referring to?

When I opened this issue (more than a year ago), the aide version was 0.16.2

The current version is 0.17.3
You can see it by clonning the ArchLinux AUR package: ttps://aur.archlinux.org/aide.git

Now I'm using Gentoo and the stable version of aide is 0.16.2_p20200614. It works well.
